### ISSUE TITLE
Add 8.7 support

### ISSUE THREAD

**Issue by quanah** [Zimbra-Community/zimbra-tools#2]
It would be nice if the script could detect 8.7 vs 8.6 and prior installs, and operate accordingly.  For example the path is different for the location to cbpolicyd.

**Comment by ghost** [comment]
I will add that tomorrow, in the mean time, going off-topic I noted that the version of cbpolicyd shipped with 8.6 is a bit dated.

The SQL code generated with ./convert-tsql has parts in it that where dropped in MySQL 5.5.

e.g. grep -lZr -e "TYPE=InnoDB" "/tmp/policyd.sql" | xargs -0 sed -i "s^TYPE=InnoDB^ENGINE=InnoDB^g"

TYPE is no longer working, and should be ENGINE... this is fixed in cbpolicyd upstream, maybe Zimbra can update the package.

**Comment by quanah** [comment]
I'll file a bug to upgrade cbpolicyd in 8.6.1

**Comment by quanah** [comment]
https://bugzilla.zimbra.com/show_bug.cgi?id=105293

**Comment by ghost** [comment]
fixed in https://github.com/Zimbra-Community/zimbra-tools/commit/5fc866cd2fc5be9cda3b1def70db1c87211e72a3
